// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeLocal(arg1:string,arg2:number,arg3:number):Promise<main.AnalyzeResult>;

export function AnalyzeRemote(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.AnalyzeResult>;

export function CheckServer(arg1:string):Promise<string>;

export function GetFrameURL(arg1:main.AnalyzeResult,arg2:string):Promise<string>;

export function SelectVideo():Promise<string>;
