// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeLocal(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeLocal'](arg1, arg2, arg3);
}

export function AnalyzeRemote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeRemote'](arg1, arg2, arg3, arg4);
}

export function CheckServer(arg1) {
  return window['go']['main']['App']['CheckServer'](arg1);
}

export function GetFrameURL(arg1, arg2) {
  return window['go']['main']['App']['GetFrameURL'](arg1, arg2);
}

export function SelectVideo() {
  return window['go']['main']['App']['SelectVideo']();
}
